import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { client } from "../lib/client";

// components
import { ButtonLarge } from "../components/atoms/ButtonLarge";
import { ButtonSmall } from "../components/atoms/ButtonSmall";
import { Navigation } from "../components/molecules/Navigation";
import { Banner } from "../components/molecules/banner";

export const getServerSideProps = async ({ locale }) => {
  const bannerQuery = `*[_type == "banner" && __i18n_lang == $lang]`;
  const banner = await client.fetch(bannerQuery, {
    lang: locale,
  });

  const navigationQuery = `*[_type == "navigation" && __i18n_lang == $lang]`;
  const navigation = await client.fetch(navigationQuery, { lang: locale });
  const pageQuery = `*[_type == "page" && __i18n_lang == $lang]`;
  const page = await client.fetch(pageQuery, { lang: locale });
  return {
    props: { banner, navigation, page },
  };
};

export default function Home({ banner, navigation, page }) {
  const router = useRouter();
  const { locale } = router;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation navigation={navigation} page={page} />
      <Banner banner={banner} />
    </div>
  );
}

{
  /* <main className="flex">
        <div className="px-6">
          <h1 className="text-Phone/Header1">Desktop</h1>
          <h1 className="font-merriweather text-Desktop/Header1">Header 1</h1>
          <h2 className="font-merriweather-bold text-Desktop/Header2">
            Header 2
          </h2>
          <h3 className="font-merriweather text-Desktop/Header3">Header 3</h3>
          <p className="font-poppins text-Desktop/Label">Label </p>
          <p className="font-poppins text-Desktop/Label underline">Label </p>
          <p className="font-merriweather text-Desktop/paragraph">paragraaf</p>
          <p className="font-merriweather text-Desktop/Quote">Quote</p>
          <button className="font-poppins text-Phone/buttonsmall">
            button text small
          </button>
          <button className="font-poppins text-Phone/buttonlarge">
            button text groot
          </button>
        </div>

        <div className="px-6">
          <h1 className="text-Phone/Header1">Phone</h1>
          <h1 className="font-merriweather text-Phone/Header1">Hello world!</h1>
          <h2 className="font-merriweather-bold text-Phone/Header2">
            Hello world!
          </h2>
          <h3 className="font-merriweather text-Phone/header3">header 3</h3>
          <p className="font-poppins text-Phone/Label">label</p>
          <p className="font-poppins text-Phone/Labelsmall">label small</p>
          <p className="font-merriweather text-Phone/paragraph">paragraaf</p>
          <p className="font-merriweather text-Phone/Quote">Quote</p>
          <button className="font-merriweather text-Phone/buttonsmall">
            button small
          </button>
          <button className="font-merriweather text-Phone/buttonlarge">
            button groot
          </button>
        </div>
      </main> */
}
